name: TimedWorldRemaker
version: '1.0'
main: com.koirdsuzu.timedworldremaker.TimedWorldRemaker
api-version: '1.20'
authors: [koirdsuzu]
description: 設定した時間でワールドデータを入れ替える。
website: https://github.com/koirdsuzu/
